FROM node:22-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app
COPY package.json ./
RUN npm install
COPY tsconfig.json ./
COPY src ./src/
RUN npm run build

EXPOSE 3001
ENV PORT=3001
CMD ["node", "dist/index.js"]
